# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - id: "cli-amd64"
    env:
      - CGO_ENABLED=0
    main: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    binary: s3cli-mini
    ldflags:
      - -s -w
      - -X github.com/shogo82148/s3cli-mini/cmd.version={{.Version}}
  - id: "cli-arm64"
    env:
      - CGO_ENABLED=0
    main: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - arm64
    binary: s3cli-mini
    ldflags:
      - -s -w
      - -X github.com/shogo82148/s3cli-mini/cmd.version={{.Version}}
archives:
  - builds:
      - cli-amd64
      - cli-arm64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: package-amd64
    builds:
      - cli-amd64
    homepage: https://github.com/shogo82148/s3cli-mini/
    maintainer: ICHINOSE Shogo <shogo82148@gmail.com>
    description: Golang port for AWS Command Line Interface S3 subcommand.
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    release: 1
    epoch: 0
    bindir: /usr/bin
  - id: package-arm64
    builds:
      - cli-arm64
    homepage: https://github.com/shogo82148/s3cli-mini/
    maintainer: ICHINOSE Shogo <shogo82148@gmail.com>
    description: Golang port for AWS Command Line Interface S3 subcommand.
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    release: 1
    epoch: 0
    bindir: /usr/bin

blobs:
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-amd64]
    directory: amazonlinux/2/x86_64/s3cli-mini
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-arm64]
    directory: amazonlinux/2/aarch64/s3cli-mini
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-amd64]
    directory: amazonlinux/2023/x86_64/s3cli-mini
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-arm64]
    directory: amazonlinux/2023/aarch64/s3cli-mini
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-amd64]
    directory: centos/7/x86_64/s3cli-mini
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-arm64]
    directory: centos/7/aarch64/s3cli-mini
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-amd64]
    directory: almalinux/8/x86_64/s3cli-mini
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-arm64]
    directory: almalinux/8/aarch64/s3cli-mini
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-amd64]
    directory: rockylinux/8/x86_64/s3cli-mini
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-arm64]
    directory: rockylinux/8/aarch64/s3cli-mini
