name: Go
on: [push, pull_request]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: golang:1.13.0-buster

    services:
      localstack:
        image: localstack/localstack:0.10.2
        ports:
        - "4572:4572"
        env:
          SERVICES: s3

    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: "1.13"

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: |
        echo $S3MINI_TEST_ENDPOINT
        /usr/bin/docker ps
        make test
      env:
        GO111MODULE: "on"
        S3MINI_TEST_ENDPOINT: "http://localhost:4572"
