name: Go
on: [push, pull_request]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack:0.10.2
        ports:
        - "4567-4584:4567-4584"

    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: "1.13"

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: make test
      env:
        GO111MODULE: "on"
