name: Go
on: [push, pull_request]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack:0.10.2
        ports:
        - "4572:4572"
        env:
          SERVICES: s3
        options: --health-cmd="/usr/bin/awslocal s3 ls" --health-start-period 10s --health-interval 10s --health-timeout 5s --health-retries 10

    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: "1.13"

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: |
        curl $S3MINI_TEST_ENDPOINT
        make test
      env:
        GO111MODULE: "on"
        LOCALSTACK: "${{ job.services.localstack.id }}"
        S3MINI_TEST_ENDPOINT: "http://localhost:4572"
