name: goreleaser

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    permissions:
      contents: write
      id-token: write
      attestations: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: go.mod
      - name: Configure AWS Credentials
        uses: fuller-inc/actions-aws-assume-role@ab8b68ccaa6a83d843cd6f9403fc3c0eb2e3af0c # v1.7.1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::445285296882:role/rpm-repository-users-S3cliMiniDeployRole-CW2G8XXL8BBY
          role-session-tagging: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
        with:
          subject-path: |
            dist/*.tar.gz
            dist/*.apk
            dist/*.deb
            dist/*.rpm
            dist/*.zip
            dist/checksums.txt
